[package]
name = "ray-tracer"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25.6", default-features = false, features = ["png", "jpeg"] }
rand = { version = "0.9.1", default-features = false, features = ["thread_rng"] }
rayon = "1.10.0"
